name: Setup Lua environment

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lua-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Running Lua Busted
            # You may pin to the exact commit or the version.
            # uses: lunarmodules/busted@02f31a9c103a44e166617cfdb6ba1b8994a9c912
        uses: lunarmodules/busted@v2.2.0
      - run: echo "Busting lua_spec files in the repository."

  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: (Super) Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
